// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: coarse_index.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CoarseIndexMetadata 粗粒度索引元数据
type CoarseIndexMetadataPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalVectors  int32                  `protobuf:"varint,1,opt,name=total_vectors,json=totalVectors,proto3" json:"total_vectors,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	MaxPages      int32                  `protobuf:"varint,4,opt,name=max_pages,json=maxPages,proto3" json:"max_pages,omitempty"`
	UsePq         bool                   `protobuf:"varint,5,opt,name=use_pq,json=usePq,proto3" json:"use_pq,omitempty"`
	PqSubspaces   int32                  `protobuf:"varint,6,opt,name=pq_subspaces,json=pqSubspaces,proto3" json:"pq_subspaces,omitempty"`
	PqCentroids   int32                  `protobuf:"varint,7,opt,name=pq_centroids,json=pqCentroids,proto3" json:"pq_centroids,omitempty"`
	PageMap       map[int32]int32        `protobuf:"bytes,8,rep,name=page_map,json=pageMap,proto3" json:"page_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // vector_id -> page_index
	LastModified  int64                  `protobuf:"varint,9,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoarseIndexMetadataPB) Reset() {
	*x = CoarseIndexMetadataPB{}
	mi := &file_coarse_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoarseIndexMetadataPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoarseIndexMetadataPB) ProtoMessage() {}

func (x *CoarseIndexMetadataPB) ProtoReflect() protoreflect.Message {
	mi := &file_coarse_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoarseIndexMetadataPB.ProtoReflect.Descriptor instead.
func (*CoarseIndexMetadataPB) Descriptor() ([]byte, []int) {
	return file_coarse_index_proto_rawDescGZIP(), []int{0}
}

func (x *CoarseIndexMetadataPB) GetTotalVectors() int32 {
	if x != nil {
		return x.TotalVectors
	}
	return 0
}

func (x *CoarseIndexMetadataPB) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *CoarseIndexMetadataPB) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CoarseIndexMetadataPB) GetMaxPages() int32 {
	if x != nil {
		return x.MaxPages
	}
	return 0
}

func (x *CoarseIndexMetadataPB) GetUsePq() bool {
	if x != nil {
		return x.UsePq
	}
	return false
}

func (x *CoarseIndexMetadataPB) GetPqSubspaces() int32 {
	if x != nil {
		return x.PqSubspaces
	}
	return 0
}

func (x *CoarseIndexMetadataPB) GetPqCentroids() int32 {
	if x != nil {
		return x.PqCentroids
	}
	return 0
}

func (x *CoarseIndexMetadataPB) GetPageMap() map[int32]int32 {
	if x != nil {
		return x.PageMap
	}
	return nil
}

func (x *CoarseIndexMetadataPB) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

// PageData 页面数据
type PageDataPB struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PageId        int32                   `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Vectors       map[int32]*VectorDataPB `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // vector_id -> vector_data
	Quantized     map[int32][]byte        `protobuf:"bytes,3,rep,name=quantized,proto3" json:"quantized,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // vector_id -> quantized_data
	LastAccess    int64                   `protobuf:"varint,4,opt,name=last_access,json=lastAccess,proto3" json:"last_access,omitempty"`
	Loaded        bool                    `protobuf:"varint,5,opt,name=loaded,proto3" json:"loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageDataPB) Reset() {
	*x = PageDataPB{}
	mi := &file_coarse_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageDataPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageDataPB) ProtoMessage() {}

func (x *PageDataPB) ProtoReflect() protoreflect.Message {
	mi := &file_coarse_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageDataPB.ProtoReflect.Descriptor instead.
func (*PageDataPB) Descriptor() ([]byte, []int) {
	return file_coarse_index_proto_rawDescGZIP(), []int{1}
}

func (x *PageDataPB) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *PageDataPB) GetVectors() map[int32]*VectorDataPB {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *PageDataPB) GetQuantized() map[int32][]byte {
	if x != nil {
		return x.Quantized
	}
	return nil
}

func (x *PageDataPB) GetLastAccess() int64 {
	if x != nil {
		return x.LastAccess
	}
	return 0
}

func (x *PageDataPB) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

// VectorDataPB 向量数据
type VectorDataPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorDataPB) Reset() {
	*x = VectorDataPB{}
	mi := &file_coarse_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorDataPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorDataPB) ProtoMessage() {}

func (x *VectorDataPB) ProtoReflect() protoreflect.Message {
	mi := &file_coarse_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorDataPB.ProtoReflect.Descriptor instead.
func (*VectorDataPB) Descriptor() ([]byte, []int) {
	return file_coarse_index_proto_rawDescGZIP(), []int{2}
}

func (x *VectorDataPB) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

// PageDirtyMap 页面脏标记映射（用于增量保存）
type PageDirtyMapPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirtyPages    []int32                `protobuf:"varint,1,rep,packed,name=dirty_pages,json=dirtyPages,proto3" json:"dirty_pages,omitempty"`
	LastSaveTime  int64                  `protobuf:"varint,2,opt,name=last_save_time,json=lastSaveTime,proto3" json:"last_save_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageDirtyMapPB) Reset() {
	*x = PageDirtyMapPB{}
	mi := &file_coarse_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageDirtyMapPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageDirtyMapPB) ProtoMessage() {}

func (x *PageDirtyMapPB) ProtoReflect() protoreflect.Message {
	mi := &file_coarse_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageDirtyMapPB.ProtoReflect.Descriptor instead.
func (*PageDirtyMapPB) Descriptor() ([]byte, []int) {
	return file_coarse_index_proto_rawDescGZIP(), []int{3}
}

func (x *PageDirtyMapPB) GetDirtyPages() []int32 {
	if x != nil {
		return x.DirtyPages
	}
	return nil
}

func (x *PageDirtyMapPB) GetLastSaveTime() int64 {
	if x != nil {
		return x.LastSaveTime
	}
	return 0
}

// CoarseIndexSnapshot 粗粒度索引快照（用于完整保存）
type CoarseIndexSnapshotPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *CoarseIndexMetadataPB `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Pages         []*PageDataPB          `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoarseIndexSnapshotPB) Reset() {
	*x = CoarseIndexSnapshotPB{}
	mi := &file_coarse_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoarseIndexSnapshotPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoarseIndexSnapshotPB) ProtoMessage() {}

func (x *CoarseIndexSnapshotPB) ProtoReflect() protoreflect.Message {
	mi := &file_coarse_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoarseIndexSnapshotPB.ProtoReflect.Descriptor instead.
func (*CoarseIndexSnapshotPB) Descriptor() ([]byte, []int) {
	return file_coarse_index_proto_rawDescGZIP(), []int{4}
}

func (x *CoarseIndexSnapshotPB) GetMetadata() *CoarseIndexMetadataPB {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CoarseIndexSnapshotPB) GetPages() []*PageDataPB {
	if x != nil {
		return x.Pages
	}
	return nil
}

var File_coarse_index_proto protoreflect.FileDescriptor

const file_coarse_index_proto_rawDesc = "" +
	"\n" +
	"\x12coarse_index.proto\x12\bprotobuf\"\x9e\x03\n" +
	"\x15CoarseIndexMetadataPB\x12#\n" +
	"\rtotal_vectors\x18\x01 \x01(\x05R\ftotalVectors\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tmax_pages\x18\x04 \x01(\x05R\bmaxPages\x12\x15\n" +
	"\x06use_pq\x18\x05 \x01(\bR\x05usePq\x12!\n" +
	"\fpq_subspaces\x18\x06 \x01(\x05R\vpqSubspaces\x12!\n" +
	"\fpq_centroids\x18\a \x01(\x05R\vpqCentroids\x12G\n" +
	"\bpage_map\x18\b \x03(\v2,.protobuf.CoarseIndexMetadataPB.PageMapEntryR\apageMap\x12#\n" +
	"\rlast_modified\x18\t \x01(\x03R\flastModified\x1a:\n" +
	"\fPageMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xf0\x02\n" +
	"\n" +
	"PageDataPB\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\x05R\x06pageId\x12;\n" +
	"\avectors\x18\x02 \x03(\v2!.protobuf.PageDataPB.VectorsEntryR\avectors\x12A\n" +
	"\tquantized\x18\x03 \x03(\v2#.protobuf.PageDataPB.QuantizedEntryR\tquantized\x12\x1f\n" +
	"\vlast_access\x18\x04 \x01(\x03R\n" +
	"lastAccess\x12\x16\n" +
	"\x06loaded\x18\x05 \x01(\bR\x06loaded\x1aR\n" +
	"\fVectorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.protobuf.VectorDataPBR\x05value:\x028\x01\x1a<\n" +
	"\x0eQuantizedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"&\n" +
	"\fVectorDataPB\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\"W\n" +
	"\x0ePageDirtyMapPB\x12\x1f\n" +
	"\vdirty_pages\x18\x01 \x03(\x05R\n" +
	"dirtyPages\x12$\n" +
	"\x0elast_save_time\x18\x02 \x01(\x03R\flastSaveTime\"\x80\x01\n" +
	"\x15CoarseIndexSnapshotPB\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.protobuf.CoarseIndexMetadataPBR\bmetadata\x12*\n" +
	"\x05pages\x18\x02 \x03(\v2\x14.protobuf.PageDataPBR\x05pagesB2Z0github.com/adnilis/x-hmsw/serialization/protobufb\x06proto3"

var (
	file_coarse_index_proto_rawDescOnce sync.Once
	file_coarse_index_proto_rawDescData []byte
)

func file_coarse_index_proto_rawDescGZIP() []byte {
	file_coarse_index_proto_rawDescOnce.Do(func() {
		file_coarse_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coarse_index_proto_rawDesc), len(file_coarse_index_proto_rawDesc)))
	})
	return file_coarse_index_proto_rawDescData
}

var file_coarse_index_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_coarse_index_proto_goTypes = []any{
	(*CoarseIndexMetadataPB)(nil), // 0: protobuf.CoarseIndexMetadataPB
	(*PageDataPB)(nil),            // 1: protobuf.PageDataPB
	(*VectorDataPB)(nil),          // 2: protobuf.VectorDataPB
	(*PageDirtyMapPB)(nil),        // 3: protobuf.PageDirtyMapPB
	(*CoarseIndexSnapshotPB)(nil), // 4: protobuf.CoarseIndexSnapshotPB
	nil,                           // 5: protobuf.CoarseIndexMetadataPB.PageMapEntry
	nil,                           // 6: protobuf.PageDataPB.VectorsEntry
	nil,                           // 7: protobuf.PageDataPB.QuantizedEntry
}
var file_coarse_index_proto_depIdxs = []int32{
	5, // 0: protobuf.CoarseIndexMetadataPB.page_map:type_name -> protobuf.CoarseIndexMetadataPB.PageMapEntry
	6, // 1: protobuf.PageDataPB.vectors:type_name -> protobuf.PageDataPB.VectorsEntry
	7, // 2: protobuf.PageDataPB.quantized:type_name -> protobuf.PageDataPB.QuantizedEntry
	0, // 3: protobuf.CoarseIndexSnapshotPB.metadata:type_name -> protobuf.CoarseIndexMetadataPB
	1, // 4: protobuf.CoarseIndexSnapshotPB.pages:type_name -> protobuf.PageDataPB
	2, // 5: protobuf.PageDataPB.VectorsEntry.value:type_name -> protobuf.VectorDataPB
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_coarse_index_proto_init() }
func file_coarse_index_proto_init() {
	if File_coarse_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coarse_index_proto_rawDesc), len(file_coarse_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coarse_index_proto_goTypes,
		DependencyIndexes: file_coarse_index_proto_depIdxs,
		MessageInfos:      file_coarse_index_proto_msgTypes,
	}.Build()
	File_coarse_index_proto = out.File
	file_coarse_index_proto_goTypes = nil
	file_coarse_index_proto_depIdxs = nil
}
