// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: vector.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorPB) Reset() {
	*x = VectorPB{}
	mi := &file_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorPB) ProtoMessage() {}

func (x *VectorPB) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorPB.ProtoReflect.Descriptor instead.
func (*VectorPB) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{0}
}

func (x *VectorPB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorPB) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *VectorPB) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VectorPB) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type VectorBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*VectorPB            `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorBatch) Reset() {
	*x = VectorBatch{}
	mi := &file_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorBatch) ProtoMessage() {}

func (x *VectorBatch) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorBatch.ProtoReflect.Descriptor instead.
func (*VectorBatch) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{1}
}

func (x *VectorBatch) GetVectors() []*VectorPB {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type SearchResultPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultPB) Reset() {
	*x = SearchResultPB{}
	mi := &file_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultPB) ProtoMessage() {}

func (x *SearchResultPB) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultPB.ProtoReflect.Descriptor instead.
func (*SearchResultPB) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResultPB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResultPB) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResultPB) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_vector_proto protoreflect.FileDescriptor

const file_vector_proto_rawDesc = "" +
	"\n" +
	"\fvector.proto\x12\bprotobuf\"\xc7\x01\n" +
	"\bVectorPB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x129\n" +
	"\apayload\x18\x03 \x03(\v2\x1f.protobuf.VectorPB.PayloadEntryR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\vVectorBatch\x12,\n" +
	"\avectors\x18\x01 \x03(\v2\x12.protobuf.VectorPBR\avectors\"\xb9\x01\n" +
	"\x0eSearchResultPB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x12?\n" +
	"\apayload\x18\x03 \x03(\v2%.protobuf.SearchResultPB.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B2Z0github.com/adnilis/x-hmsw/serialization/protobufb\x06proto3"

var (
	file_vector_proto_rawDescOnce sync.Once
	file_vector_proto_rawDescData []byte
)

func file_vector_proto_rawDescGZIP() []byte {
	file_vector_proto_rawDescOnce.Do(func() {
		file_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_proto_rawDesc), len(file_vector_proto_rawDesc)))
	})
	return file_vector_proto_rawDescData
}

var file_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_vector_proto_goTypes = []any{
	(*VectorPB)(nil),       // 0: protobuf.VectorPB
	(*VectorBatch)(nil),    // 1: protobuf.VectorBatch
	(*SearchResultPB)(nil), // 2: protobuf.SearchResultPB
	nil,                    // 3: protobuf.VectorPB.PayloadEntry
	nil,                    // 4: protobuf.SearchResultPB.PayloadEntry
}
var file_vector_proto_depIdxs = []int32{
	3, // 0: protobuf.VectorPB.payload:type_name -> protobuf.VectorPB.PayloadEntry
	0, // 1: protobuf.VectorBatch.vectors:type_name -> protobuf.VectorPB
	4, // 2: protobuf.SearchResultPB.payload:type_name -> protobuf.SearchResultPB.PayloadEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vector_proto_init() }
func file_vector_proto_init() {
	if File_vector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_proto_rawDesc), len(file_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vector_proto_goTypes,
		DependencyIndexes: file_vector_proto_depIdxs,
		MessageInfos:      file_vector_proto_msgTypes,
	}.Build()
	File_vector_proto = out.File
	file_vector_proto_goTypes = nil
	file_vector_proto_depIdxs = nil
}
